export const CREATE_FORM_POINT_API = '/formulario/crear';
export const LOGIN_POINT_API = '/auth/login';
export const GET_FORM_POINT_API = "/formulario";
export const getFormByIdPointApi = (id) => `/formulario/${id}`;
export const getReviewFormPointApi = (id) => `/formulario/${id}/revisar`;
export const getTeachingSubjectFormPointApi = (id) => `/formulario/${id}/asignatura-docencia`;
export const getWorkActivitiesFormPointApi = (id) => `/formulario/${id}/actividades-laborales`;
export const getTeachingActivitiesFormPointApi = (id) => `/formulario/${id}/actividades-docencia`;
export const getScientificActivitiesFormPointApi = (id) => `/formulario/${id}/actividades-cientificas`;
export const getAdministrativeActivitiesFormPointApi = (id) => `/formulario/${id}/actividades-administrativas`;
export const getPersonPointApi = (id) => `/persona/${id}`;